REPORT_COLUMNS = [
    "County",
    "MCD Name",
    "GEOID10",
    "YEAR",
    "POPULATION_ESTIMATE"
    "TOTAL_CRASH_RATE",
    "TOTAL_KILLED_RATE",
    "TOTAL_INJURED_RATE",
    "PEDESTRIANS_KILLED_RATE",
    "PEDESTRIAN_INJURY_RATE",
    "BICYCLISTS_KILLED_RATE"
    "BICYCLISTS_INJURED_RATE",
    "TOTAL_CRASH_RATE_5YR",
    "TOTAL_KILLED_RATE_5YR",
    "TOTAL_INJURED_RATE_5YR",
    "PEDESTRIANS_KILLED_RATE_5YR",
    "PEDESTRIAN_INJURY_RATE_5YR",
    "BICYCLISTS_KILLED_RATE_5YR"
    "BICYCLISTS_INJURED_RATE_5YR",
]